### ISSUE TITLE
[FIX] Frontend is still calling APIs to localhost

### ISSUE THREAD

**Issue by aryad14** [mlscgescoe/pixelStack#7]
## Issue
The frontend is making API calls to backend running on the localhost. Currently hosted website is not connected to the backend, hence the login and register functions do not work

## Required Solution
The backend server is hosted on Render - [Click here to preview](https://pixelstack.onrender.com)
On clicking the hosted backend link above, it should show a hello world message in JSON format. If it does, the backend is working perfectly.
The Solution needed is to store the API link in an environment variable, and the frontend app components should call the APIs using the link stored in the enviroment variable
Also provide a **.env.sample** file, which includes the Environment variable name which has the environment variable stored

**Comment by Jash2606** [comment]
Hey @aryad14  ,
I would like to contrubute for this issue , under the hacktoberfest 2024 !

**Comment by Rasheedatj** [comment]
Hello @aryad14 I have gone through your codebase and understand what needs to be done. I simply have to create a .env file and save the base url link there and also add the base url value to environment variables on render. Kindly assign this task to me so I can fix it
